### ISSUE TITLE
Are private chats still blocked

### ISSUE THREAD

**Issue by ethanfrey** [joeyates/electric-sql-chat-demo#1]
I’m excited about trying out electric sql and precisely for multi channel chats (with some permissions who can see what). I read

> N.B. Until the [work on shapes](https://electric-sql.com/docs/reference/roadmap#shapes) progresses, it will not be possible to have private chats where users only have access to messages that have been sent to/by them.

I don’t find the roadmap link any more, but rather https://electric-sql.com/docs/guides/shapes

Could you let me know if it is possible to provide per channel permissioning now? I’d love to try to add it to this app, if there are docs how to do so

**Comment by ethanfrey** [comment]
Does https://github.com/electric-sql/electric/pull/1566 solve this?

**Comment by joeyates** [comment]
Hi @ethanfrey 

I'm afraid I've lost track of ElectricSQL since I did this demo, so I'm unaware of what progress has been made.

As I'm doing other things, I'm not currently intending to update this demo.

As to your question about Shapes, the [Shapes documentation](https://electric-sql.com/docs/guides/shapes) certainly seems to indicate that they are now usable. So a project like this one could now have proper separation between the data of the various users.

**Comment by ethanfrey** [comment]
Thank you for the response.
